version: "3"
services:
  selfassessment-backend:
    container_name: selfassessment-backend
    restart: always
    image: selfassessment-backend
    build: .
    volumes:
      - ./.env:/usr/src/app/.env
      - ./data/assets:/usr/src/app/data/assets
      - ./data/configs:/usr/src/app/data/configs
    ports:
      - "8000:8000"
    links:
      - mongo
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
